name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [3.2, 3.3]
    env:
      repo: "govpf/cypress"
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.0

    - name: Build and push
      uses: docker/build-push-action@v6.1.0
      with:
        context: .
        file: ./${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}
